module.exports = {
    ok: "success",
    userRegister: "Your Register Successful",
    QuoteAdded: "Quote added successfully",
    NotFound: "Record Not Found",
    NotApproved: "Your Account Has Not Been Approved Till Yet",
    emailAlreadyExist: "Record Already Exist",
    updateSuccess: "Updated successfully",
    deleteSuccess: "Deleted successfully",
    incorrectPassword: "Incorrect Email or Password",
    incorrectOldPassword: "Your password is incorrect",
    passwordUpdate: "Password update successfull",
    emailSent: "Mail has been sent",
    serverError: "Internal Server Error",
    validationErrors: "Validation Errors",
    empytyField: "Please Enter",
    chargeMethod: "Charge Method is not created",
    RefundCreated: "Refund Generated",
    RefundNotGenrated: "Refund Not Genrated",
    PaymentIntentCreated: "Payment Intent Created",
    paymentUpdate: "Payment Not Updated",
    paymentCapture: "Payment Not Captured",
    paymentConfirm: "Payment Charged",
    unAuthorized: "You are unauthorized to perfome this action",
    recordNotCreated: "Record not created",
    checkEmail: "Please Check Email"
  };
  